#!/usr/bin/env python3

"""Reject first-party identifiers retired by the Axio style migration."""

from __future__ import annotations

import re
import sys
from pathlib import Path


SOURCE_SUFFIXES = {".cc", ".h", ".hh"}

# Keep this list explicit. It is extended as each subsystem is migrated so a
# review commit can turn the newly added checks from red to green in one batch.
RETIRED_IDENTIFIERS = (
    "_unused",
    "likely",
    "unlikely",
    "KB",
    "MB",
    "GB",
    "CEIL_2",
    "PERF_TEST",
    "PERF_TEST_LAT",
    "PERF_TEST_THR",
    "PERF_TEST_LAT_MIN_MAX",
    "PERT_TEST_MBUF_RANGE",
    "PERF_LAT_SAMPLE_STRIP",
    "PERF_LAT_SAMPLE_NUM",
    "PERF_LAT_USE_RDTSCP",
    "CLIENT",
    "SERVER",
    "NODE_TYPE",
    "ENABLE_TUNE",
    "ENABLE_AXIO_TEST",
    "msg_handler_type_t",
    "kRxMsgHandler_Empty",
    "kRxMsgHandler_T_APP",
    "kRxMsgHandler_L_APP",
    "kRxMsgHandler_M_APP",
    "kRxMsgHandler_FS_WRITE",
    "kRxMsgHandler_FS_READ",
    "kRxMsgHandler_KV",
    "RoceMode",
    "DpdkMode",
    "RoCE_TYPE",
    "DISPATCHER_TYPE",
    "MEM_REG_TYPE",
    "pkt_handler_type_t",
    "kRxPktHandler_Empty",
    "kRxPktHandler_Echo",
    "kRxMsgHandler",
    "ApplyNewMbuf",
    "kRxPktHandler",
    "EnableInflyMessageLimit",
    "OneStage",
    "FlowSize",
    "kInvaildWorkspaceType",
    "kTxNICType",
    "kTxDispatcherType",
    "kTxApplicationType",
    "kRxNICType",
    "kRxDispatcherType",
    "kRxApplicationType",
    "RESET",
    "RED",
    "GREEN",
    "YELLOW",
    "BLUE",
    "mem_reg_info",
    "get_name",
    "get_mem_reg",
    "kLocalIpStr",
    "kRemoteIpStr",
    "kLocalMac",
    "kRemoteMac",
    "kDPDK",
    "kRoCE",
    "collect_tx_pkts",
    "tx_flush",
    "rx_burst",
    "dispatch_rx_pkts",
    "pkt_handler_client",
    "pkt_handler_server",
    "get_tx_queue_size",
    "get_rx_queue_size",
    "add_ws_tx_queue",
    "get_ws_tx_queue_size",
    "add_ws_rx_queue",
    "add_rx_rule",
    "get_used_mbuf_num",
    "get_rx_used_desc",
    "ownership_memzone_t",
    "kRemoteMngtIpStr",
    "get_epoch",
    "get_num_qps_available",
    "get_summary",
    "get_qp",
    "free_qp",
    "daemon_reclaim_qps_from_crashed",
    "setup_phy_port",
    "fill_tx_pkts",
    "fill_rx_pkts",
    "get_rx_queue_index",
    "tx_burst_for_arp",
    "is_arp_packet",
    "handle_arp_packet",
    "echo_handler",
    "get_mempool_name",
    "dpdk_strerror",
    "get_mempool",
    "offload_flow_rules",
    "clear_flow_rules",
    "drain_rx_queue",
    "dpdk_mbuf_alloc",
    "dpdk_mbuf_alloc_bulk",
    "dpdk_mbuf_de_alloc",
    "dpdk_mbuf_de_alloc_bulk",
    "dpdk_set_mbuf_paylod",
    "dpdk_extracr_ws_hdr",
    "dpdk_cp_payload",
    "dpdk_mbuf_extract_ws_hdr",
    "dpdk_mbuf_cp_payload",
    "TOTAL_HEADER_LEN",
    "mbuf_eth_hdr",
    "mbuf_ip_hdr",
    "mbuf_tcp_hdr",
    "mbuf_udp_hdr",
    "mbuf_ws_hdr",
    "mbuf_ws_payload",
    "mbuf_ip6_hdr",
    "mbuf_icmp6_hdr",
    "mbuf_push_eth_hdr",
    "mbuf_push_arphdr",
    "mbuf_push_iphdr",
    "mbuf_push_ip6_hdr",
    "mbuf_push_tcphdr",
    "mbuf_push_udphdr",
    "mbuf_push_ws_hdr",
    "mbuf_push_data",
    "mbuf_print",
    "RTE_PKTMBUF_PUSH",
    "routing_info_t",
    "ib_routing_info_t",
    "IBResolve",
    "kRQDepth",
    "kSQDepth",
    "kMemRegionSize",
    "kQKey",
    "kGRHBytes",
    "kMaxDataPerPkt",
    "kDefaultGIDIndex",
    "create_ah",
    "fill_local_routing_info",
    "roce_resolve_phy_port",
    "init_verbs_structs",
    "init_mem_reg_funcs",
    "init_recvs",
    "init_sends",
    "set_local_qp_info",
    "set_remote_qp_info",
    "post_recvs",
    "resolve_pkt_hdr",
    "tx_burst",
    "roce_mbuf_alloc",
    "roce_mbuf_alloc_bulk",
    "roce_mbuf_de_alloc",
    "roce_mbuf_de_alloc_bulk",
    "roce_set_mbuf_paylod",
    "roce_extracr_ws_hdr",
    "roce_cp_payload",
    "shm_region_t",
    "DoRegister",
    "k_min_class_size",
    "k_min_class_bit_shift",
    "k_max_class_size",
    "k_num_classes",
    "kAllocFailHelpStr",
    "get_numa_node",
    "get_stat_shm_reserved",
    "get_stat_user_alloc_tot",
    "print_stats",
    "get_class",
    "get_class_slow",
    "alloc_from_class",
    "reserve_hugepages",
    "free_buf",
    "alloc_raw",
    "kPOSTED",
    "kAPP_OWNED_BUF",
    "kFREE_BUF",
    "buffer_print",
    "get_buf",
    "get_buf_offset",
    "get_ws_payload",
    "get_ws_hdr",
    "get_uh",
    "get_iph",
    "enum_to_mtu",
    "link_layer_str",
    "poll_cq_one_helper",
    "ibdev2netdev",
    "common_resolve_phy_port",
    "kMagicWrIDForFastRecv",
    "kModdedProbeWrID",
    "kModdedProbeRet",
    "SlowRand",
    "FastRand",
    "SharedMemBuf",
    "defaultBuferSize",
    "defaultControlRegionSize",
    "recv_data",
    "unused_len",
    "used_len",
    "copy_in_helper",
    "copy_out_helper",
    "KV",
    "key_t",
    "value_t",
    "HashFunc",
    "CompareFunc",
    "dpath_rdtsc",
    "TCPClient",
    "TCPServer",
    "connectToServer",
    "sendMsg",
    "receiveMsg",
    "QPInfo",
    "MAX_HOSTNAME_LEN",
    "MAX_NIC_NAME_LEN",
    "mgnt_server",
    "mgnt_client",
    "net_stats",
    "perf_stats",
    "net_stats_app_tx",
    "net_stats_app_rx",
    "net_stats_app_tx_duration",
    "net_stats_app_tx_stall_duration",
    "net_stats_app_rx_duration",
    "net_stats_app_rx_stall_duration",
    "net_stats_app_tx_mbuf_reuse_interval",
    "net_stats_disp_tx",
    "net_stats_disp_rx",
    "net_stats_disp_tx_duration",
    "net_stats_disp_tx_stall_duration",
    "net_stats_disp_rx_duration",
    "net_stats_disp_rx_stall_duration",
    "net_stats_nic_tx",
    "net_stats_nic_rx",
    "net_stats_nic_tx_duration",
    "net_stats_nic_rx_duration",
    "net_stats_nic_rx_cpt",
    "net_stats_app_apply_mbuf_stalls",
    "net_stats_app_drops",
    "net_stats_mbuf_usage",
    "net_stats_disp_enqueue_drops",
    "net_stats_init",
    "perf_stats_init",
    "print_perf_stats",
    "disp_mbuf_usage",
    "eth_addr",
    "eth_hdr",
    "eth_addr_is_zero",
    "eth_addr_copy",
    "eth_addr_swap",
    "eth_hdr_set",
    "eth_addr_to_str",
    "eth_addr_init",
    "ETH_ADDR_LEN",
    "ETH_ADDR_STR_LEN",
    "arp_hdr_t",
    "ETH_P_ARP",
    "ETH_P_IP",
    "ETH_ALEN",
    "ARPHRD_ETHER",
    "ARPOP_REQUEST",
    "ARPOP_REPLY",
    "ipaddr_t",
    "ipaddr_join",
    "ipaddr_last_byte",
    "ipaddr_eq",
    "ipaddr_init",
    "ipaddr_inc",
    "ip_hdr_get_addr_low32",
    "iph_swap_addr",
    "ip6h_swap_addr",
    "IP6_ADDR_SIZE",
    "IP_FLAG_DF",
    "IPV4_STR",
    "IPV4_FMT",
    "IPV6_STR",
    "IPV6_FMT",
    "ipv4_from_str",
    "ws_hdr",
    "phase_t",
    "alloc_t",
    "alloc_bulk_t",
    "de_alloc_t",
    "de_alloc_bulk_t",
    "set_payload_t",
    "extract_ws_hdr_t",
    "cp_payload_t",
    "dispatcher_mr_",
    "alloc_",
    "de_alloc_",
    "alloc_bulk_",
    "de_alloc_bulk_",
    "extract_ws_hdr_",
    "cp_payload_",
    "DISPATCHER",
    "WORKER",
    "NIC_OFFLOAD",
    "DISPATCHER_AND_WORKER",
)

RETIRED_PATTERN = re.compile(
    r"\b(?:" + "|".join(re.escape(name) for name in RETIRED_IDENTIFIERS) + r")\b"
)
RETIRED_MACRO_PATTERN = re.compile(r"^\s*#\s*define\s+(?:UD|RC)\b")


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {Path(sys.argv[0]).name} REPOSITORY_ROOT", file=sys.stderr)
        return 2

    root = Path(sys.argv[1]).resolve()
    violations: list[str] = []
    for path in sorted((root / "src").rglob("*")):
        if not path.is_file() or path.suffix not in SOURCE_SUFFIXES:
            continue
        for line_number, line in enumerate(
            path.read_text(encoding="utf-8").splitlines(), start=1
        ):
            match = RETIRED_PATTERN.search(line)
            macro_match = RETIRED_MACRO_PATTERN.search(line)
            if match or macro_match:
                relative_path = path.relative_to(root)
                violations.append(
                    f"{relative_path}:{line_number}: retired identifier "
                    f"{match.group(0) if match else macro_match.group(0).split()[-1]}"
                )

    if violations:
        print("retired Axio style identifiers found:", file=sys.stderr)
        for violation in violations:
            print(f"  {violation}", file=sys.stderr)
        return 1

    print("Axio style guard passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
