#pragma once

#define AXIO_CONFIG_NODE_TYPE 0
#define AXIO_CONFIG_DPDK_MODE 0
#define AXIO_CONFIG_ROCE_MODE 1
#define AXIO_CONFIG_ROCE_TRANSPORT_TYPE 0
#define AXIO_CONFIG_MTU 4096
#define AXIO_CONFIG_RX_RING_ENTRIES 1024
#define AXIO_CONFIG_TX_RING_ENTRIES 512
#define AXIO_CONFIG_MEMPOOL_SIZE 16384
#define AXIO_CONFIG_MEMPOOL_HANDLER 9
#define AXIO_CONFIG_MEMPOOL_CACHE_SIZE 64
#define AXIO_CONFIG_MESSAGE_HANDLER 2
#define AXIO_CONFIG_PACKET_HANDLER 1
#define AXIO_CONFIG_APPLY_NEW_MBUF 1
#define AXIO_CONFIG_REQUEST_PAYLOAD_BYTES 86
#define AXIO_CONFIG_RESPONSE_PAYLOAD_BYTES 86
#define AXIO_CONFIG_APP_TICKS_PER_MESSAGE 7
#define AXIO_CONFIG_INFLIGHT_LIMIT_ENABLED 0
#define AXIO_CONFIG_INFLIGHT_MESSAGES 77
